---
title: "About"
about:
  template: solana
  links:
  - icon: github
    text: GitHub
    href: https://github.com/jasminex21
  - icon: twitter 
    text: Twitter
    href: https://x.com/lyriguessr
  - icon: instagram
    text: Instagram
    href: https://www.instagram.com/lyriguessr  
  - icon: linkedin
    text: LinkedIn
    href: https://www.linkedin.com/in/jasminexu21/
---

### About me

Hi! I'm Jasmine, the developer of lyriguessr. I study Statistics & Data Science and Computer Science at UT Austin, and love working on projects such as lyriguessr in my free time. 

> Business inquiries: contact me at <lyriguessr@gmail.com>!

The idea of lyriguessr all started with tayLyrics, the Taylor Swift-themed game I initially created for myself and my roommate Hannah during my freshman year. We're both Swifties and are avid tayLyrics players - try to beat us on the leaderboard!

I realized that tayLyrics could be generalized to any artist - why not share the fun with everyone, right? And so lyriguessr was born.

> My favorite artists are Waterparks, Bad Omens, and Taylor Swift. Follow me on Spotify [here](https://open.spotify.com/user/bananaslug-10?si=4d7ef41b24c54ac5)!

### Acknowledgements

A couple people I'd like to thank for their contributions to lyriguessr's development...

* My roommate (and the love of my life) Hannah, whose love for (and *insane* competency at) tayLyrics inspired the creation of lyriguessr
* Jiant, for his business insights
* Trus, for designing the amazing lyriguessr logo